kind: Service
apiVersion: v1
metadata:
  name: simpleserver-{{.Replica}}-{{.Iteration}}
spec:
  selector:
    name: simpleserver-{{.Replica}}-{{.Iteration}}
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  portalIP: ''
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}