---
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: false
    esServers: [http://elastic-elk.apps.rsevilla.kube-burner.com]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic
  measurements:
    - name: podLatency
      esIndex: kube-burner

jobs:
  - name: kubelet-density-simple-heavy
    jobIterations: {{ .JOB_ITERATIONS }}
    qps: 25
    burst: 25
    namespacedIterations: false
    namespace: kubelet-density-simple-heavy
    waitWhenFinished: true
    podWait: false
    objects:

      - objectTemplate: templates/simpleserver-deployment.yml
        replicas: 1

      - objectTemplate: templates/simpleapp-deployment.yml
        replicas: 1
        inputVars:
          readinessPeriod: 10

      - objectTemplate: templates/simpleserver-service.yml
        replicas: 1
